# To complete task perticular schedule given.
kind: CronJob
apiVersion: batch/v1
metadata:
  name: demo-cronjob
  namespace: nginx
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
  spec:
   template:
     metadata:
      name: minute-backup
      labels:
       app: minute-backup
     spec: 
     containers:
     - name: backup-container
       image: busybox:latest
       command:
       - sh
       - -c
       - >
         echo"Backup started";
         mkdir -p /backups &&
         mkdir -p /demo-data &&
         cp -r /demo-data /backups &&
         echo "Backup Completed" ;
     volumeMounts :
       - name: data-volume
         mountPath: /demo-data
       - name: backup-volume
         mountPath: /backups
         restartPolicy: OnFailure
         volumes:
          - name: data-volume
            hostPath:
              path: /demo-data
              type: DirectoryOrCreate
          - name: backup-volume
            hostPath:
              path: /backups
              type: DirectoryOrCreate
    