# To complete task given.Pod status will be completed
kind: Job
apiVersion: batch/v1
metadata:
  name: demo-job
  namespace: nginx
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:  
  containers:
    name: demo-job-pod
    labels:
      app: batch-task
  spec:
    containers:
    - name: batch-container
      image: busybox:latest
      command: ['sh','-c','echo hello world && sleep 10']
    restartPolicy: Never
    